#Koduppgift 2

### Uppgift 9

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split, GridSearchCV

from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor

from sklearn.metrics import mean_absolute_error, mean_squared_error

a) Läs in datasetet “data_01.csv” med funktionen read_csv() från Pandas. Funktionen returnerar en DataFrame

In [5]:
df = pd.read_csv('./dataset/data_01.csv')

In [6]:
df.head(5)

         x1        x2        x3        x4        x5      target
0  0.743487  1.072825  1.332911 -1.244771  0.344978  220.173943
1  0.835264  0.202184  0.966480  0.745883 -0.033773  175.873929
2 -1.103234  0.030615 -0.140385  0.727683 -2.831224 -162.270054
3  1.210186  1.685258 -0.394123  0.719024 -2.166585  165.930461
4  0.474577  0.647737 -0.451812 -0.409472 -0.051473   43.250511

b) Dela upp datasetet i X och y.

In [12]:
X = df.drop('target', axis=1)
y = df['target']

In [17]:
X.head()

         x1        x2        x3        x4        x5
0  0.743487  1.072825  1.332911 -1.244771  0.344978
1  0.835264  0.202184  0.966480  0.745883 -0.033773
2 -1.103234  0.030615 -0.140385  0.727683 -2.831224
3  1.210186  1.685258 -0.394123  0.719024 -2.166585
4  0.474577  0.647737 -0.451812 -0.409472 -0.051473

In [18]:
y.head()

0    220.173943
1    175.873929
2   -162.270054
3    165.930461
4     43.250511
Name: target, dtype: float64

c) Dela upp datan ytterligare, i ett träning-, ett validering-, och ett testset med train_test_split(). Låt 20% av datan vara testdata och 15% av den återstående datan vara valideringsdata.

In [19]:
X_train_val, x_test, y_train_val, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
X_train, X_val, y_train, y_val = train_test_split(X_train_val, y_train_val, test_size=0.15, random_state=40)

d) Träna två valfria regressionsmodeller (exempelvis LinearRegression och DecisionTreeRegressor) på träningsdatan. Notera, i kapitel 3 kommer vi lära oss mer om DecisionTreeRegressor.

**Linear Regression Model**

In [20]:
lin_reg = LinearRegression()
lin_reg.fit(X_train, y_train)
lin_reg_pred = lin_reg.predict(X_val)

**Decision Tree Regression**

In [24]:
dt_reg = DecisionTreeRegressor()
dt_reg.fit(X_train, y_train)
dt_pred = dt_reg.predict(X_val)

Jag känner att jag inte ville köra en gridsearch på den här för att det är i kapitel 3 i boken. och det kändes tråkigt att bara skriva av kod exemplet.

e) Utvärdera modellerna på valideringsdatan

In [25]:
def regression_metrics(y_true, y_pred):
    return {
        'MAE': mean_absolute_error(y_true, y_pred),
        'RMSE': np.sqrt(mean_squared_error(y_true, y_pred))
    }

validation_results = pd.DataFrame({
    'Linear Regression': regression_metrics(y_val, lin_reg_pred),
    'Decision Tree': regression_metrics(y_val, dt_pred)
}).T

validation_results

                         MAE       RMSE
Linear Regression   2.603697   3.379782
Decision Tree      74.869471  94.944958

f) Träna om den bäst presterande modellen på både tränings- och valideringsdatan.

g) Utvärdera modellen på testdatan.

h) Träna om modellen på hela datasetet

### Uppgift 10

a) Läs in datasetet “salary_dataset.csv” med pandas read_csv()-funktion och dela upp i X och y. Avgör själv vilken variabel som ska vara den beroende variabeln y

b) Dela upp datasetet i träning- och testset. (Inget validerings-set alltså!)

c) Träna två regressionsmodeller med k-delad korsvalidering med cross_validate()-funktionen från scikit-learn. Använd neg_root_mean_squared_error som scoring. Välj själv hur många iterationer den ska göra genom hyperparametern cv.

d) Utvärdera modellen som presterar bäst på testsetet.

### Uppgift 11

a) Läs in datasetet mpg med seaborns load_dataset()-funktion (det gjordes i koden ovan)

b) Droppa rader med saknade värden med dropna()-metoden.

c) Droppa kolumnen name

d) Utför en dummy-variable-encoding på origin-kolumnen med pandas get_dummies()-funktion. Ange drop_first=True så att vi får 2 nya kolumner istället för 3

e) Dela upp datasetet i X och y, med mpg som den beroende variabeln y

f) Dela upp datasetet i träning- och testset

g) Träna en linjär regressionsmodell på träningsdatan och utvärdera den på testdatan